version: "3.8"
services:
  cards:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    # links:
    #   - database
    # depends_on:
    #   - database
  # database:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     MYSQL_USER: 'user'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - .mysql:/var/lib/mysql