# Generated by Django 3.2.13 on 2023-06-18 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fromm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('to', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
            ],
        ),
    ]
