# Generated by Django 3.2.13 on 2024-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_options', '0004_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pocketed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='yes', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('evaluate', 'Evaluate')], default='evaluate', max_length=200),
        ),
    ]
