# Generated by Django 3.2.13 on 2024-02-10 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_options', '0005_auto_20240210_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='kind',
            field=models.CharField(choices=[('stock', 'Stock'), ('put', 'Put'), ('call', 'Call'), ('div', 'Dividends')], default='stock', max_length=200),
        ),
    ]
